version: "3"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - /home/csgoserver/serverfiles/csgo:/usr/share/nginx/html/svdownload/csgo
    ports:
      - "80:80"
    restart: "always"
#   db:
#     image: mysql:5.7
#     restart: always
#     environment:
#       MYSQL_DATABASE: 'sourcemod'
#       MYSQL_ROOT_PASSWORD: '${mysql_password}'
#     ports:
#       - '3306:3306'
#     volumes:
#       - sourcemod-db:/var/lib/mysql
# volumes:
#   sourcemod-db:
